# The MIT License (MIT)
#
# Copyright (c) 2023 Xiaoyang Chen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import codecs
from enum import IntEnum
from typing import Union, List
from . import interop
from .interop import AutoPtr, LL_TRUE

class Completion:
    """A completion task that given a llm Model and complete the input prompt."""
    def __init__(self, comp_c_ptr: AutoPtr) -> None:
        self._pcomp = comp_c_ptr
        self._pchunk = AutoPtr(interop.create_chunk(), interop.destroy_chunk)

    def __iter__(self):
        utf8_decoder = codecs.getincrementaldecoder("utf-8")()
        while interop.is_active(self._pcomp.get()) == LL_TRUE:
            interop.get_next_chunk(self._pcomp.get(), self._pchunk.get())
            piece = interop.get_chunk_text(self._pchunk.get())
            chunk_text = utf8_decoder.decode(piece)
            if chunk_text:
                yield Chunk(text=chunk_text)

        # remaining bytes in utf8_decoder
        chunk_text = utf8_decoder.decode(b"", final=True)
        if chunk_text:
            yield Chunk(text=chunk_text)

class Device(IntEnum):
    CPU =  0x0000
    CUDA = 0x0100
    AUTO = 0x1f00

class ControlToken:
    """Represents a control token in the prompt, for example <|user|>."""
    def __init__(self, token_name: str) -> None:
        self._name = token_name

class Model:
    """Model in libllm."""
    def __init__(self, config_file: str, device: Device = Device.AUTO) -> None:
        """Create an instance of Model from the libLLM model config file. When device is
        Device.AUTO, it will automatically choose the best device to load. Otherwise load model to
        the specified device.
        Args:
            config_file (str): config of the libLLM model.
            device (Device): target computation device.
        """
        self._pmodel = AutoPtr(interop.create_model(), interop.destroy_model)
        interop.set_model_config(self._pmodel.get(), config_file.encode("utf-8"))
        interop.set_model_device(self._pmodel.get(), int(device))
        interop.load_model(self._pmodel.get())

    @property
    def name(self):
        model_name = interop.get_model_name(self._pmodel.get())
        return model_name.decode("utf-8")

    def complete(self, prompt: Union[str, List[Union[str, ControlToken]]], top_k: int = 50,
                 top_p: float = 0.8, temperature: float = 1.0) -> None:
        """Compelete the prompt with given generation settings. The prompt could be either a string
        or a list of [string|SpecialToken] (when special_token is need).
        """
        pprompt = self._prepare_prompt(prompt)
        pcomp = AutoPtr(interop.create_completion(self._pmodel.get()), interop.destroy_completion)
        interop.set_top_k(pcomp.get(), top_k)
        interop.set_top_p(pcomp.get(), top_p)
        interop.set_temperature(pcomp.get(), temperature)
        interop.set_prompt(pcomp.get(), pprompt.get())

        interop.start_completion(pcomp.get())
        return Completion(pcomp)

    def _prepare_prompt(self, prompt: Union[str, List[Union[str, ControlToken]]]):
        pprompt = AutoPtr(interop.create_prompt(self._pmodel.get()), interop.destroy_prompt)
        if isinstance(prompt, str):
            interop.append_text(pprompt.get(), prompt.encode("utf-8"))
        elif isinstance(prompt, list):
            for block in prompt:
                if isinstance(block, str):
                    interop.append_text(pprompt.get(), block.encode("utf-8"))
                elif isinstance(block, ControlToken):
                    interop.append_control_token(pprompt.get(), block._name.encode("utf-8"))
                else:
                    raise NotImplementedError()
        else:
            raise NotImplementedError()
        
        return pprompt

class Chunk:
    """a chunk of text generated by llm (in Completion)."""
    def __init__(self, text: str) -> None:
        self.text = text
